### ISSUE TITLE
[BUG] Chunks stop loading/generating

### ISSUE THREAD

**Issue by MasterKyle08** [YassaaaTU/ALOE#4]
Server chunks stopped loading and a error was given saying that it failed to save chunks. Never loaded chunks after that

**MC Info:**
Modloader Version:  40.1.68
Modpack Version: Alpha-0.1.2

Started server, first error was when it went online, then joined and it loaded spawn chunk and gave the second error. Never loaded any other chunks after that

Chunks should load

I have 12gb ram and 5 cpu cores shouldnt be hardware limitations. It was using 11.56 gb/12 which is really high. It was working fine with 7gb assigned to  it the other day

https://mclo.gs/Cg1ubFE

**Comment by YassaaaTU** [comment]
Ok I'm about to go to sleep so a quick fix would be removing Danny's Expansion mod and trying again.
You need to remove/disable the mod from both the server and the client side

And if you disable/remove Danny's expansion mod then you can also do the same to its library mod called braincellAPI because no other mods use it.

Im planning an update later next week where either the mod is removed or updated with a bigfix

**Comment by MasterKyle08** [comment]
when I removed this twilight forest gave error when loading

log: https://mclo.gs/eSkNBrP

Crash text: https://mclo.gs/42NVYW3

![error 1 ALOE modpack](https://user-images.githubusercontent.com/59895881/181565917-b6a14249-abf2-4ce7-8679-e3b63e8621bb.png)

**Comment by YassaaaTU** [comment]
the error with twilight forest occurs from time to time a relaunch should do the trick.

An update of the mod was released 2 days ago that has hopefully fixed this error.
